# Generated by Django 2.2 on 2019-07-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='timestamp',
            new_name='add_timestamp',
        ),
    ]
