# Generated by Django 2.2 on 2019-07-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190704_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-edited_date', '-add_timestamp']},
        ),
    ]
