# Generated by Django 2.2 on 2019-07-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190713_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-add_timestamp', '-edited_date']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
    ]
