# Generated by Django 2.2 on 2019-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190713_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='Good blog post lol', max_length=100),
            preserve_default=False,
        ),
    ]
