# Generated by Django 2.2 on 2019-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('add_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_timestamp'],
            },
        ),
    ]
