# Generated by Django 2.2 on 2019-08-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('add_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_timestamp'],
            },
        ),
    ]
