# Generated by Django 2.2 on 2019-08-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daysofcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daylog',
            name='dayInternal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
